# because you want reproducibility (in a few years you will thank me)
FROM alpine:latest AS build

# The Hugo version
ARG VERSION=0.68.3

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz /hugo.tar.gz
RUN tar -zxvf hugo.tar.gz
RUN /hugo version

# We add git to the build stage, because Hugo needs it with --enableGitInfo
RUN apk update && apk add --no-cache curl gcc git libc-dev

# The source files are copied to /blog
COPY . /blog
WORKDIR /blog

# And then we just run Hugo
RUN /hugo --minify --enableGitInfo

# stage 2
FROM nginx:1.21.0-alpine

WORKDIR /usr/share/nginx/html/

# Clean the default public folder
RUN rm -fr * .??*

# Finally, the "public" folder generated by Hugo in the previous stage
# is copied into the public fold of nginx
COPY --from=build /blog/public /usr/share/nginx/html