name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy blog
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_DO}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_DO_USERNAME }} # User of the server you want to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          script: | 
            pwd
            echo 'Deployment successful to digital ocean'
